<a href="https://colab.research.google.com/github/Thitichaya2000/multivariate/blob/main/MVA001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Scalar, Vector, Matrix


#Scalar

In [9]:
  import numpy as np

In [10]:
scalar_a = 10  #scalar
print(scalar_a)

10


#Vector

In [12]:
vector_b = np.zeros([2,1])
vector_b[0,0] = 1
vector_b[1,0] = 3
print(vector_b)
print(vector_b.shape)

[[1.]
 [3.]]
(2, 1)


In [15]:
vector_c = np.array([[1],[3]])
print(vector_c)
print(vector_c.shape)

[[1]
 [3]]
(2, 1)


In [16]:
from  matplotlip import pyplot as plt

ModuleNotFoundError: ignored

ขนาดของ vector คำนวณได้โดย พีทาโกรัส

In [ ]:
 1 vector_b_size = ()

#Matrix

In [17]:
matrix_d = np.array([[2,3],[1,4],[-1,1]])
print(matrix_d )

[[ 2  3]
 [ 1  4]
 [-1  1]]


In [18]:
matrix_d = matrix_d.T
print(matrix_d )

[[ 2  1 -1]
 [ 3  4  1]]


In [24]:
matrix_d[0,:]

array([ 2,  1, -1])

In [29]:
plt.plot(matrix_d[0, :],(matrix_d[1, :], 'or' )  ##plot(ค่าx, ค่าy, หน้าตาของจุด)
plt.plot(0,0, '.b' )  
plt.plot([0,0],[-1,5], '--b' )
plt.plot([-1.5,2.5],[0,0], '--b' )

SyntaxError: ignored